### ISSUE TITLE
 CRITICAL Uncaught TypeError: Cannot access offset of type string on string in /var/www/html/wp-content/plugins/btcpay-for-woocommerce/class-wc-gateway-btcpay.php:499

### ISSUE THREAD

**Issue by webyacusa** [btcpayserver/woocommerce-plugin#69]
I installed the BTCPay plugging on my ubuntu 20.04 server. It has PHP 8.0.11 and Apache 2. The installation completes successfully. When I try to go to WooCommerce -> Settings -> Payments and I select the setup button next to BTCPay, the configuration screen does not shows any of the options that usually does:

![screenshot1](https://user-images.githubusercontent.com/7103866/147866948-37d89490-b71a-45f3-a490-b0be42c71b47.png)

 

** Woocommerce System Status **

**WooCommerce Plugin Logs (if applicable)**

> 2022-01-02T05:03:20+00:00 CRITICAL Uncaught TypeError: Cannot access offset of type string on string in /var/www/html/wp-content/plugins/btcpay-for-woocommerce/class-wc-gateway-btcpay.php:499
> Stack trace:
> #0 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php(329): WC_Gateway_BtcPay->generate_order_states_html()
> #1 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-settings-api.php(85): WC_Settings_API->generate_settings_html()
> #2 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php(194): WC_Settings_API->admin_options()
> #3 /var/www/html/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php(104): WC_Payment_Gateway->admin_options()
> #4 /var/www/html/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php(87): WC_Settings_Payment_Gateways->run_gateway_admin_options()
> #5 /var/www/html/wp-includes/class-wp-hook.php(303): WC_Settings_Payment_Gateways->output()
> #6 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
> #7 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action()
> #8 /var/www/html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-settings.php(40): do_action()
> #9 /var/www/html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(153): include('...')
> #10 /var/www/html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(273): WC_Admin_Settings::output()
> #11 /var/www/html/wp-includes/class-wp-hook.php(303): WC_Admin_Menus->settings_page()
> #12 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
> #13 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action()
> #14 /var/www/html/wp-admin/admin.php(259): do_action()
> #15 {main}
>   thrown in /var/www/html/wp-content/plugins/btcpay-for-woocommerce/class-wc-gateway-btcpay.php on line 499

**Your BTCPay Environment (please complete the following information):**

- BTCPay Server Version:     v1.3.7.0 (Although this info is irrelevant since I can't enter the server info yet on the configuration
- Deployment Method:        Digital Ocean Droplet
- Browser:                  Chrome, Firefox

**Additional context**

**Screenshots / Video / GIf (if applicable)**

**Comment by NicolasDorier** [comment]
First time I see this. Can you try to tweak the code in the line `class-wc-gateway-btcpay.php:499`, to see more about what is going on?
